### ISSUE TITLE
What's the meaning of min_mean in generate_blurred_dataset.m?

### ISSUE THREAD

**Issue by ChenyangLiu** [marcelampc/d3net_depth_estimation#1]
https://github.com/marcelampc/d3net_depth_estimation/blob/413dca7aeb64c6aab2f90c4c929516a2a47d2a43/matlab/generate_blurred_dataset.m#L34

Should line 34 be mean2(im) > min_mean?

**Comment by marcelampc** [comment]
I used to test an internal dataset and ignore dark images. I've juste removed this part of the code! Thank you for asking.
