### ISSUE TITLE
Test issues

### ISSUE THREAD

**Issue by Fannzi** [marcelampc/d3net_depth_estimation#10]
Hi, thanks for the great work.
I've trained your network with my dataset, and wish to test its accuracy, however the following error occured.
![image](https://user-images.githubusercontent.com/62327668/171545031-90512f7d-3db4-4b97-ac84-2a759974b1cb.png)
But I failed to find "last_common_layer.0" name issues in the original code. Hope you can give some help.

**Comment by taewookum** [comment]
me too.... please share the test_dfd.sh file.
