### ISSUE TITLE
What's the parameter.m for your paper?

### ISSUE THREAD

**Issue by ChenyangLiu** [marcelampc/d3net_depth_estimation#2]
Hi,

What's the parameter.m for you paper? I can't correspond your variable name with the camera parameters. Would you please give parameters used in paper for NYU? Thank you!

**Comment by marcelampc** [comment]
Hi! Now you have the parameters for both experiments:

[parameters_blurred_NYUv2.m](https://github.com/marcelampc/d3net_depth_estimation/blob/master/matlab/parameters_blurred_NYUv2.m)
[parameters_DFD_indoor.m](https://github.com/marcelampc/d3net_depth_estimation/blob/master/matlab/parameters_DFD_indoor.m)

I had indeed forgot to add them here!
