### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by wrongchen7** [marcelampc/d3net_depth_estimation#3]
How to use the code generate_blurred_dataset.m?

**Comment by marcelampc** [comment]
Hi!
Here are the steps to make it work:

**Dataset**
First you need to have some dataset with corresponding pairs of rgb and depth maps. You can download NYUv2 from here https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html to perform same experiments as in papers. You can just download the [Toolbox](http://cs.nyu.edu/~silberman/code/toolbox_nyu_depth_v2.zip) and the small split of the dataset ([Labeled dataset (~2.8 GB)](http://horatio.cs.nyu.edu/mit/silberman/nyu_depth_v2/nyu_depth_v2_labeled.mat)).

**Preprocess data**
Depth maps must be aligned, cropped and invalid depth values (missing) must be filled-in (it's all in the NYUv2 Toolbox).

**Blur**
Now, you just have to change lines 30-34 to define the paths to the rgb and to the depth maps and the destination paths for the resulting data (blurred rgb and same depth maps).

Code expects depth maps in millimeters and saves as uint16 also in milimeters.

Hope this helps!
