### ISSUE TITLE
the interval of inputs and ground truth

### ISSUE THREAD

**Issue by anmeizhang** [marcelampc/d3net_depth_estimation#5]
My depth ground truth are true depth values (from 0m to 10m), but the outputs of tanh are  within [-1, 1], I notice your dataset is also NYU v2. So I want to ask what is your depth ground truth? By the way, are your input images in the interval [0, 1] or [0, 255]?   I am looking forward for your answers. Thank you!

**Comment by marcelampc** [comment]
Hi! You may just delete the Tanh layer! I was working with GAN algorithms at first and used the Tanh to have values between -1 and 1 for the discriminator. I stopped using this layer now to output value in meters and save them in milimeters.
