### ISSUE TITLE
running the network with pytorch

### ISSUE THREAD

**Issue by Fannzi** [marcelampc/d3net_depth_estimation#7]
hi, thanks for the work!
I was trying to run the network with pytorch with "python main.py  --dataroot [root] --name [testdata]", but failed to get any progress. 
Do training datasets need to be downloaded and added to the file manually? Is it convenient to have any pretained network parameters open?

**Comment by marcelampc** [comment]
Hello, I'll try to update this repo to the new pytorch. To answer your question, yes, you should download manually. For the pretrained weights, it will automatically download densenet ones.
